### ISSUE TITLE
Multiple PopUp

### ISSUE THREAD

**Issue by mirus-ua** [fraina/react-popupbox#10]
Hi there. I'm need a help. All my PopUp's open at the same time. This is my component. How can I fix this problem? 

`import React, { Component, Fragment } from 'react';
import {
    PopupboxManager,
    PopupboxContainer
} from 'react-popupbox';
import { render } from 'react-dom';
import Cover from './Cover'
import Slider from './Slider'

export class PhotoPopUp extends Component {
    constructor(props) {
        super(props)

        this.openPopupbox = this.openPopupbox.bind(this)
    }
    openPopupbox() {
        const content = (
            <Slider gallery={this.props.gallery}/>
        )
        PopupboxManager.open({ 
            content,
            config: {
                style: {
                    height: '90vh'
                },
                className: 'mainPopUpClass'
            }
         })
       

    }
    
    render() {
        return (
            <Fragment>
                <div onClick={this.openPopupbox}><Cover cover={this.props.gallery}/></div>
                <PopupboxContainer style={{height: '100%'}}/>
            </Fragment>
        )
    }
}`

**Comment by fraina** [comment]
Hi @Miruzz, there should be only one instance of `PopupboxContainer` in your app. If there are multiple `PopupboxContainer`, all of them will be opened when you fire `PopupboxManager.open()`.

Just change the `content` parameter of `PopupboxManager.open()` when you need different content to show.
