### ISSUE TITLE
can't do the update popupbox

### ISSUE THREAD

**Issue by TEDinTW** [fraina/react-popupbox#11]
when I try to do update popupbox with new content or config.

<img width="703" alt="2018-07-19 2 25 11" src="https://user-images.githubusercontent.com/532771/42925144-b99b88ca-8b5f-11e8-9cff-b98070117349.png">

I can open the popupbox ,but can't do the next update

I'm wondering if I do something wrong ?

part of my component 
`class PopupBox extends Component {
  updatePopup_box() {
    const content = (
      <div>
        <span>Update popupbox with new content and config</span>
        <button onClick={PopupboxManager.close}>Close</button>
      </div>
    );
    PopupboxManager.update({
      content,
      config: {
        titleBar: {
          text: 'Updated!',
        },
      },
    });
  }

  openPopup_box() {
    const content = (
      <div>
        <span>Open popupbox</span>
        <button onClick={this.updatePopup_box()}>Update!</button>
      </div>
    );
    PopupboxManager.open({
      content,
      config: {
        titleBar: {
          enable: true,
          text: 'Step 1',
        },
        fadeIn: true,
        fadeInSpeed: 500,
      },
    });
  }
  render() {
    return (
      <div>
        <button onClick={this.openPopup_box}>Click</button>
        <PopupboxContainer />
      </div>
    );
  }
}

export default PopupBox;`

=============
part of my App.js
`import PopupBox from './component/popupbox/PopupBox';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <PopupBox />
      </div>
    );
  }
}

export default App;`

**Comment by fraina** [comment]
Please remove the parentheses of `this.updatePopup_box()` and see if popupbox update as expected.

Please let me know if it is not. :)

**Comment by fraina** [comment]
Uh and you need to bind `this.updatePopup_box` to `PopupBox` for provide particular `this` value, like you can add the following code into `PopupBox` component:
```
constructor() {
  super()
  this.updatePopup_box = this.updatePopup_box.bind(this)
}
```

**Comment by TEDinTW** [comment]
Hi, thanks for your quick answer.
I tried to modify as the following . 
<img width="489" alt="2018-07-20 10 42 34" src="https://user-images.githubusercontent.com/532771/43008731-5e5a72cc-8c6e-11e8-8386-bdedcc068b7e.png">
<img width="473" alt="2018-07-20 10 42 48" src="https://user-images.githubusercontent.com/532771/43008817-973e33a8-8c6e-11e8-86f9-1dfc31d5fc6c.png">

But it still can't work.
<img width="753" alt="2018-07-20 10 45 57" src="https://user-images.githubusercontent.com/532771/43008855-ba996796-8c6e-11e8-8f65-810e14bb0726.png">

Finally,  the following code can work.
<img width="480" alt="2018-07-20 10 49 29" src="https://user-images.githubusercontent.com/532771/43009059-35591daa-8c6f-11e8-8cec-f23335eef5a9.png">

As I'm a newbie to react, I'm not sure if this can cause some side effect or not?

Thanks for your help, again.

**Comment by fraina** [comment]
A static member won't be able to access `this`, it would be okay if there's no need to get properties or methods of the class. More details please refer to [Static Methods in ES6](https://medium.com/@yyang0903/static-objects-static-methods-in-es6-1c026dbb8bb1).
Btw seems this issue is more related to ES6 syntax usage than `Popupbox` itself, I'll close this by now. Please feel free to reopen if there is any other issue. :)
