### ISSUE TITLE
Need a way to refresh content

### ISSUE THREAD

**Issue by stan014** [Fraina/react-popupbox#2]
First all, thanks for this fantastic plugin!
While using, I cannot find a way/method to `refresh` the content in popupbox,
My suggestion is  to add the following to `Container.js`:
```
  handleStoreChange(params) {
    const { children, show, config } = params;

    if (this.state.show !== show) {
      ....
    }
    else(
      this.update(children)
    )
  }
  update(children){
    this.setState(state=>{
      return {
        ...state,
        children
      }
    })
  }
```

**Comment by Fraina** [comment]
Hi, sorry for my late reply.
It seems like you are intend to refresh/replace entire content, this plugin was designed for display pop-up message in the first place. However, I'm thinking to add a new public method named 'refresh' or 'update'.
You may also check my other repo: [react-imagebox](https://github.com/Fraina/react-imagebox), maybe it will fit your need.

**Comment by Fraina** [comment]
I've add a new method named `update`, feel free to reopen this issue if it can't solve your case.
