### ISSUE TITLE
Popup Title Bar Removed when Opened

### ISSUE THREAD

**Issue by rmspeers** [fraina/react-popupbox#6]
Using the default JS and CSS, with the parameters set in the config as follows, the titleBar is being removed from the DOM (not just left hidden) when I activate the popup.

    render() {
        const popupboxConfig = {
            titleBar: {
                enable: true,
                text: 'My Title'
            },
            fadeIn: true,
            fadeInSpeed: 500
        }

        return (
            <div>
                <button onClick={this.openPopupbox}>Do Popup</button>
                <PopupboxContainer { ...popupboxConfig } />
            </div>
        )
    }

The popup opens, but it shows only what I provide to `PopupboxManager.open()` as content, it does NOT show any title.

This can be resolved by providing the titleBar parameters also in the arguments to `PopupboxManager.open()` along with the content. It appears that what is passed (or not passed) here overrides the settings on the `PopupboxContainer`. This doesn't seem logical and doesn't seem to match what I see in the examples.

Filing this for your consideration of updating this behavior.

**Comment by fraina** [comment]
Hi @rmspeers, thanks for taking your time to report this issue, I'm looking into this.

**Comment by fraina** [comment]
Just release a new version v2.0.4 to fix this default config bug, title bar should work as expected now. :)
Feel free to reopen this issue if the new version doesn't solve your case, Happy coding!
