### ISSUE TITLE
Close button not rendered

### ISSUE THREAD

**Issue by efpapado** [fraina/react-popupbox#7]
Hi,
the close button does not seem to render.
I think it is related to another problem that I notice:
The `.popupbox-wrapper` element is getting a class `.undefined`, and also the `.popupbox-titleBar` is getting a class `.[object Object]`

**Comment by fraina** [comment]
Hi, @efpapado, thank you for taking your time to report this issue, I'm looking into it.

**Comment by fraina** [comment]
The new version v2.0.5 should solve all those bugs, please let me know if it not. Thank you very much! :)
