### ISSUE TITLE
Modal not working correctly

### ISSUE THREAD

**Issue by Danielev8** [fraina/react-popupbox#8]
When the pop up is supposed to appear, it just appears within the page as its content but not as a modal even though I have tried to just copy the usage.. It appears like this image attached

![image](https://user-images.githubusercontent.com/26262489/40572757-226d4082-60a4-11e8-84e6-2111fb343857.png)

**Comment by fraina** [comment]
Hi, @Danielev8. Looks like default stylesheet is not imported into your project or it wasn't loaded correctly. With `react-popupbox.css` imported, Popupbox should work like the demo page. :)

**Comment by fraina** [comment]
Close this issue for now cause there is no more discussion.
