### ISSUE TITLE
Disabling overlayClose generates warning

### ISSUE THREAD

**Issue by mvuajua** [fraina/react-popupbox#9]
When disabling closing the popup on click on the overlay with `overlayClose: false` in the config, the following warning is emitted:

> Warning: Expected `onClick` listener to be a function, instead got `false`.
> 
> If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead.

It works either way, but it would of course be nicer without the warning.

Culprit is this line here: https://github.com/fraina/react-popupbox/blob/238ce2ea8e9b41ad0c42e51c11c2a6494332a406/src/lib/container.js#L149

Which should be 

```
this.state.overlayClose ? this.closeImagebox : undefined
```

instead of 

```
this.state.overlayClose && this.closeImagebox
```

for the click handler.

Happy to submit a PR too if wanted.

**Comment by fraina** [comment]
Hi @mvuajua, thank you so much for reporting this. 
The new version 2.0.7 should work without emitting this kind of warning, please let me know if the warning still showing. :)

**Comment by mvuajua** [comment]
@fraina that was quick, thanks! I'm currently testing things out with a fork of mine, as I needed to disable the close on esc functionality as well, but I will report back when we go back to your published version (unless you're up for implementing that option as well, might be useful? feel free to check out my fork, or I can submit a PR)
